@FinancialAccountManagement.API_HostAddress = https://localhost:7259

GET {{FinancialAccountManagement.API_HostAddress}}/api/account

###

GET {{FinancialAccountManagement.API_HostAddress}}/api/account/2

###



POST {{FinancialAccountManagement.API_HostAddress}}/api/account
Content-Type: application/json

{
  "accountNumber": "ACC888",
  "accountHolder": "Sakamoto",
  "balance": 888.00
}

###

PUT {{FinancialAccountManagement.API_HostAddress}}/api/account/6
Content-Type: application/json

{
  "accountHolder": "Taro Sakamoto",
  "balance": 999.00
}

###

DELETE {{FinancialAccountManagement.API_HostAddress}}/api/account/6

###


GET {{FinancialAccountManagement.API_HostAddress}}/api/transaction

###

GET {{FinancialAccountManagement.API_HostAddress}}/api/transaction/8

###

POST {{FinancialAccountManagement.API_HostAddress}}/api/transaction
Content-Type: application/json

{
  "accountId": 1,
  "transactionType": "Withdrawal",
  "amount": 5500.00
}

###


POST {{FinancialAccountManagement.API_HostAddress}}/api/transaction
Content-Type: application/json

{
  "accountId": 1,
  "transactionType": "Deposit", 
  "amount": 3000.00
}

###

PUT {{FinancialAccountManagement.API_HostAddress}}/api/transaction/11
Content-Type: application/json

{
  "accountId": 1,
  "transactionType": "Withdrawal",
  "amount": 50080.00
}

###



PUT {{FinancialAccountManagement.API_HostAddress}}/api/transaction/12
Content-Type: application/json

{
  "accountId": 1,
  "transactionType": "Deposit",
  "amount": 9000.00
}

###


DELETE {{FinancialAccountManagement.API_HostAddress}}/api/transaction/12

###

GET {{FinancialAccountManagement.API_HostAddress}}/api/statistics/low-balance/2

###

GET {{FinancialAccountManagement.API_HostAddress}}/api/reports/low-balance/0

###

GET {{FinancialAccountManagement.API_HostAddress}}/api/reports/low-balance/0

###

GET {{FinancialAccountManagement.API_HostAddress}}/api/reports/transactions/2

###

GET {{FinancialAccountManagement.API_HostAddress}}/api/reports/total-balance

###

GET {{FinancialAccountManagement.API_HostAddress}}/api/reports/low-balance/1500

###

GET {{FinancialAccountManagement.API_HostAddress}}/api/reports/top-accounts/5

###
